# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
{
    "name": "SQL Export Mail",
    "version": "16.0.2.0.2",
    "category": "Generic Modules",
    "summary": "Send csv file generated by sql query by mail.",
    "author": "Akretion,GRAP,Odoo Community Association (OCA)",
    "maintainers": ["legalsylvain"],
    "website": "https://github.com/OCA/reporting-engine",
    "depends": [
        "mail",
        "sql_export",
    ],
    "license": "AGPL-3",
    "data": [
        "views/sql_export_view.xml",
        "data/mail_template.xml",
    ],
    "installable": True,
}
