# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.6.1
_src_path: git+https://github.com/OCA/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: true
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'This repository hosts alternative reporting engines to the ones
  included on Odoo core (RML, QWeb and Webkit).


  The convention is to use a suffix to each module to indicate that it''s for using
  with that report engine (for example, account_invoice_report_birt or sale_order_report_pentaho).


  It can contain also another utilities directly involved with reports (like merge/split
  utils, checkers, signing tools and so on).'
repo_name: OCA alternative reporting engines and reporting utilities for Odoo
repo_slug: reporting-engine
repo_website: https://github.com/OCA/reporting-engine
travis_apt_packages:
- swig
- libreoffice
travis_apt_sources: []
