[project]
name = "odoo-addons-oca-reporting-engine"
version = "19.0.20260910.0"
dependencies = [
    "odoo-addon-base_comment_template==19.0.*",
    "odoo-addon-bi_sql_editor==19.0.*",
    "odoo-addon-kpi==19.0.*",
    "odoo-addon-pdf_xml_attachment==19.0.*",
    "odoo-addon-report_async==19.0.*",
    "odoo-addon-report_context==19.0.*",
    "odoo-addon-report_csv==19.0.*",
    "odoo-addon-report_partner_address==19.0.*",
    "odoo-addon-report_positioned_image==19.0.*",
    "odoo-addon-report_py3o==19.0.*",
    "odoo-addon-report_qweb_element_page_visibility==19.0.*",
    "odoo-addon-report_qweb_encrypt==19.0.*",
    "odoo-addon-report_qweb_field_option==19.0.*",
    "odoo-addon-report_qweb_parameter==19.0.*",
    "odoo-addon-report_wkhtmltopdf_param==19.0.*",
    "odoo-addon-report_xlsx==19.0.*",
    "odoo-addon-report_xlsx_helper==19.0.*",
    "odoo-addon-report_xml==19.0.*",
    "odoo-addon-sql_request_abstract==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
